server:
  port: 8761 # Default port for Eureka server

eureka:
  client:
    register-with-eureka: false # This server should not register itself with another Eureka server
    fetch-registry: false     # This server should not try to fetch registry information from another Eureka server
  server:
    wait-time-in-ms-when-sync-empty: 0 # Optional: Speeds up startup for a single dev instance. Remove for production.
    # Other server-specific configurations can go here